# Generated by Django 3.0.8 on 2023-07-09 07:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecomePublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('corporate_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('company', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('intro', models.TextField()),
                ('no_of_report', models.IntegerField()),
                ('yearly_published', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Publisher Partner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('corporate_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('contact_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ContactUs',
            },
        ),
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Our Clients',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publishers/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('keyword', models.CharField(max_length=1000)),
                ('meta_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('summary', ckeditor.fields.RichTextField()),
                ('tabel_of_content', ckeditor.fields.RichTextField()),
                ('list_of_figures', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('published_date', models.DateField()),
                ('no_of_pages', models.IntegerField(default=100)),
                ('single_user_price', models.IntegerField(default=2000)),
                ('corporate_user_price', models.IntegerField(default=4000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('corporate_email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(max_length=14)),
                ('job_title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('request_type', models.CharField(blank=True, choices=[('Request Sample', 'Request Sample'), ('Request Discount', 'Request Discount'), ('Request Inquiry', 'Request Inquiry'), ('COVID-19 Request', 'COVID-19 Request')], max_length=30, null=True)),
                ('lead_date', models.DateField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Billing_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('corporate_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
            options={
                'verbose_name_plural': 'BillingDetails',
            },
        ),
    ]
