# Generated by Django 3.0.8 on 2023-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20230715_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='meta_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
